package io.github.amsonix.molt

import java.io.File

/** 解析 res/raw/keep.xml 中 tools:keep 声明的资源条目。 */
object ResourceKeepParser {

    fun parseKeepXml(xml: String): List<ResourceKeepResource> {
        val keepBody = TOOLS_KEEP_REGEX.find(xml)?.groupValues?.get(1).orEmpty()
        if (keepBody.isBlank()) return emptyList()
        return RESOURCE_ENTRY_REGEX.findAll(keepBody)
            .map { ResourceKeepResource(type = it.groupValues[1], name = it.groupValues[2]) }
            .distinct()
            .toList()
    }

    fun mergeKeepXmlFiles(files: Iterable<File>): List<ResourceKeepResource> =
        files.flatMap { file ->
            if (!file.isFile) emptyList() else parseKeepXml(file.readText())
        }.distinct()

    fun formatKeepXml(
        entries: List<ResourceKeepResource>,
        generatedByTask: String,
    ): String {
        val keepLine = entries.joinToString(",\n        ") { it.toKeepToken() }
        return """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!--
            |  Generated by $generatedByTask — 动态资源 keep 列表（build 时注入，不写入源码）。
            |-->
            |<resources xmlns:tools="http://schemas.android.com/tools"
            |    tools:keep="
            |        $keepLine" />
            |
        """.trimMargin() + "\n"
    }

    private val TOOLS_KEEP_REGEX = Regex("""tools:keep="([\s\S]*?)"""")
    private val RESOURCE_ENTRY_REGEX = Regex("""@(\w+)/([^,\s]+)""")
}
